server:
  port: ${PORT:8080}

spring:
  application:
    name: gestion-vuelos

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gestion_vuelos?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  thymeleaf:
    cache: false

app:
  mail:
    remitente: ${MAIL_USERNAME:jdmoreno159@gmail.com}
    remitente-nombre: "Gestion de Vuelos"
    habilitado: true
    brevo:
      api-key: ${BREVO_API_KEY:}
  admin:
    nombre: admin
    clave: ${APP_ADMIN_CLAVE:******}
    email: ${APP_ADMIN_EMAIL:jdmoreno159@gmail.com}